### ISSUE TITLE
Measure performance of functions on different backends

### ISSUE THREAD

**Issue by RasmusSkytte** [ssi-dk/SCDB#20]
Presently we test for correctness of the functions we provide within the package.
I suggest that we expand our testing to look at the performance of our functions on different backend. 
By benchmarking our functions in this way, we can detect cases where our implementation is disproportionately ineffective (if these cases exist).
Furthermore, we can be transparent to the user when/if our Quality-of-Life implementations present substantial decreases in performance.

**Comment by marcusmunch** [comment]
When testing is enabled for additional backends, I would also suggest some kind of metric to gauge how fast (and well) each backend works and present it somewhere easily accessible.
