### ISSUE TITLE
Failing CRAN incomming checks (rc-v0.2.0)

### ISSUE THREAD

**Issue by RasmusSkytte** [ssi-dk/SCDB#45]
Incoming checks for latest commit to CRAN has 1 ERROR and 1 NOTE.

## ERROR:
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Error ('test-connection.R:17:3'): get_connection warns about unsupported backend ──
    Error: unable to find an inherited method for function 'dbCanConnect' for signature 'drv = "character"'

## NOTE:
  Non-standard file/directory found at top level:
    'README.tex'

**Comment by marcusmunch** [comment]
For autolinking purposes: This is related to #40 🙂

**Comment by marcusmunch** [comment]
Regarding README.tex: It seems that the [default option is to remove .tex after rendering](https://bookdown.org/yihui/rmarkdown/pdf-document.html#keeping-intermediate-tex), so I would guess it was only kept because something went wrong while building. I would try resubmitting
