### ISSUE TITLE
Test coverage for PostgreSQL functionality

### ISSUE THREAD

**Issue by marcusmunch** [ssi-dk/SCDB#7]
Commit eda9026c2d1cc60e55efc27d3b8122b90582e094 skips coverage for backend-specific functions in get_table.R (more specifically, recursively retrieving tables within schemas).

While the lines of code in question definitely may be tested, doing so requires access to a PostgreSQL database for testing. While PostgreSQL support was what started the SCDB package in the olden days, it is *technically* not a requirement (but definitely a **very** desirable element), and the RPostgres package has been "demoted" to Suggests.

In order to remove the coverage skip on functions specific to PostgreSQL[^1], I suggest the following should be done:

- [ ] Write tests which cover the lines in question.
    * [ ] BONUS: #4 describes a case where `table_exists()` may return >1 match. Write a test covering this
- [ ] Update README.md with information on setting up a PostgreSQL server on localhost[^2].

[^1]: This really applies to any backend, but as PostgreSQL is the package's most supported backend which doesn't live in a file, it would make sense to start with this.
[^2]: Current state of get_connection does not specify any default parameters for a PostgreSQL driver, which therefore (hopefully) falls back to [.pgpass](https://www.postgresql.org/docs/15/libpq-pgpass.html) configuration.

**Comment by marcusmunch** [comment]
A semi-whole other way to go about improving PostgreSQL support could be to define a GitHub Action to [use a Docker container](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) in order to test a connection with `RPostgres::RPostgres()`.

It's not ideal for development, as local testing is limited, but hopefully it's possible to return a useful log file/error message from the action and use that for development, but I would guess forking a repo would include GitHub Actions (including checks) so that users opening a PR would know in advance if their changes break a supported backend.

**Comment by RasmusSkytte** [comment]
This website has some useful info on different ways to setup databases as part of the Github workflows:
https://ldarren.medium.com/number-of-ways-to-setup-database-in-github-actions-2cd48df9faae

**Comment by marcusmunch** [comment]
Using a docker image in a GitHub Action is definitely interesting, but probably more for the long haul, as I'm not very proficient in either. It's definitely something I want to learn, though, so hopefully this issue will be revisited in the (as near as possible) future!
