### ISSUE TITLE
Implement consistent handling of temporary tables

### ISSUE THREAD

**Issue by marcusmunch** [ssi-dk/SCDB#76]
As the package evolves from solving a problem in a specific environment to general usage, an increasingly large need to decide on a more standardized behavior has become clear, which may or may not include a large rework of the testing suite so that we define the intended return values for functions and test that this behavior is consistent across all backends.[^1]

The questions to be answered by this standard includes&mdash;and is definitely not limited to:
* Should temporary tables be listed in `get_tables`?
* Which schema(ta) should be shown for SQLite
  - If both "temp" and "main" have tables?
  - If only one of them has tables?
  - If neither has tables?
* What **does** `get_schema` actually return?
  - The schema where a table being created with a `DBI::Id` without `schema` will be put?
  - The schema where `dplyr::tbl` will currently return a table specified with a name string instead of `in_schema`?
* How should various functions behave if `schema`&mdash;and soon `catalog` as well&mdash; is not found in a `DBI::Id` instance?

[^1]: &hellip;which is what I thought we were currently doing, but here we are somehow 🤷

**Comment by RasmusSkytte** [comment]
Fixed as of https://github.com/ssi-dk/SCDB/pull/93
