### ISSUE TITLE
Add testing framework for Microsoft SQL Server

### ISSUE THREAD

**Issue by marcusmunch** [ssi-dk/SCDB#78]
**Describe the feature**

Extend the existing unit testing to also test on a Microsoft SQL Server (MSSQL) instance. Most likely by using the new and improved workflows from the https://github.com/ssi-dk/AEF-DDF repository.

**What use will this feature have?**

Other than being a requirement for _full_ support, I expect test coverage to improve, as #77 introduce many&mdash;directly or indirectly&mdash;MSSQL specific features, and simply testing on this backend naturally improves test coverage, which sits at a miserable 83.85% as of ffaf1b1 😇

**Who should add the feature?**

I could attempt to make the changes myself, but as I am leaving the SSI organisation in three weeks, someone else (\*cough @RasmusSkytte \*cough) should probably see it through.

**Additional context**

**Comment by RasmusSkytte** [comment]
I am already working on finalising the work flows for this purpose :) 

https://github.com/ssi-dk/diseasystore/pull/111

**Comment by marcusmunch** [comment]
I figured so 😊 Part of my reason for opening this issue was also to link the PR so there is an apparent (and easily fixed!) cause of the sudden drop in coverage.

**Comment by RasmusSkytte** [comment]
Let's keep this issue open until it is adapted to `SCDB` and merged into the code base.

I will migrate it once it works on `diseasystore`
