### ISSUE TITLE
FEATURE: Use SQLite as default `drv` in `get_connection`.

### ISSUE THREAD

**Issue by marcusmunch** [ssi-dk/SCDB#84]
**Describe the feature**
Change the default argument to `drv` in `get_connection()` from `RPostgres::Postgres()` to `RSQLite::SQLite`

**What use will this feature have?**
`RPostgres::Postgres()` as default `drv` argument in `get_connection()` was inherited from a package (for internal use) from which SCDB basically is forked.

Instead of an actual database backend, SQLite "connects" to files and do not require any external setup, as opposed to Postgres. Additionally, SQLite is currently a dependency on Imports level, while RPostgres is in Suggests.

This means that calling `get_connection()` on a fresh install will never succeed, even if the user has correctly configured a `.pgpass` file, as the `RPostgres` package itself is not available unless installing SCDB with all dependencies. By contrast, calling `get_connection(drv = RSQLite::SQLite())` actually works, as a temporary database is then created if none is specified.

Additionally, using `RSQLite::SQLite()` as default would simplify many examples, which currently specify `RSQLite::SQLite()` in order to be able to connect, otherwise failing `R CMD check`s.

**Who should add the feature?**
No files in `R/`, `tests/` or `vignettes/` call `get_connection()` without specifying `drv = RSQLite::SQLite()`, so the changes themselves should be no hassle to apply. So I consider myself very capable of writing it myself 😄 

However, the changes will naturally be breaking changes and should therefore be made with care. I therefore also understand if it is considered unnecessary or for other reason will set aside for now.

**Additional context**
N/A

**Comment by RasmusSkytte** [comment]
In my opinion, it would be great to set `RSQLite::SQLite()` as the default for a fresh installation.

For quality-of-life, it would be ideal if the `get_connection` arguments could be sent via options. 
This way, a user could configure their favourite data base on a per-project basis and just call `get_connection()`

**Comment by marcusmunch** [comment]
That seems a bit overkill IMO for a number of reasons:

1. `getOption` always returns a string, while connections are made with function calls. Configuring a data base from options therefore potentially allows arbitrary code execution, which I think is outside the scope of the SCDB package.

1. Executing code on a per-project basis can already be done through a user's `.Rprofile`. If you wish to run the same `.Rprofile` across multiple projects, have your `~/.Rprofile` run that code, e.g. by checking if the output from `getwd()` or (if you wanna get fancy) `rstudioapi::getActiveProject()`.
